language: python
matrix:
  include:
    - dist: xenial
python:
  - "3.8.0"
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/numpy/* -m tests.suite
after_success:
  coveralls