language: python
matrix:
  include:
    - dist: xenial
python:
  - "3.8.0"
install:
  - pip install -r requirements.txt
script:
  - coverage run -m tests.suite --source=megachess

after_success:
  coveralls