language: python
matrix:
  include:
    - dist: xenial
python:
  - "3.8.0"
install:
  - pip install -r requirements.txt
script:
  - python3 -m unittest -v tests.test_board
  - python3 -m unittest -v tests.test_pieces
  - python3 -m unittest -v tests.test_scans