language: python
matrix:
  include:
    - dist: xenial
python:
  - "3.8.0"
install:
  - pip install -r requirements.txt
script:
  - python3 -m tests.suite
  - coverage run -m tests.suite

after_success:
  coveralls